name: CI
on:
  push:
    branches:
      - master
      - unstable
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            cpu: amd64
          - os: linux
            cpu: i386
          - os: macos
            cpu: amd64
          - os: windows
            cpu: amd64
        branch: ['1.2.18', '1.6.8']
        include:
          - target:
              os: linux
            builder: ubuntu-20.04
          - target:
              os: macos
            builder: macos-12
          - target:
              os: windows
            builder: windows-2019

    defaults:
      run:
        shell: bash

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }} (Nim ${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '${{ matrix.branch }}'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.15.5'

      - name: Install p2pd
        run: |
          V=1 bash scripts/build_p2pd.sh p2pdCache 124530a3

      - name: Run tests
        run: |
          nim --version
          nimble --version
          nimble install_pinned
          nimble test
