name: Test Legacy Platforms
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

  push:

jobs:
  call-multi-nim-common:
    uses: status-im/nim-libp2p/.github/workflows/multi_nim_common.yml@fix/make-matrix-include-customizable
    with:
      nim-branch: "[
          'version-1-6',
          'version-2-0'
        ]"
      platform: "[
          {'os':'linux','cpu':'i386'}
        ]"
      includes: "[
          {
            'target': {
              'os': 'linux'
            },
            'builder': 'ubuntu-20.04',
            'shell': 'bash'
          }
        ]"

